### ISSUE TITLE
ESP nodes: decrease delay time in loop() to improve responsiveness?

### ISSUE THREAD

**Issue by khaledhassan** [khaledhassan/HAS#14]
https://github.com/khaledhassan/HAS/blob/509ca071d19776bacb1e5be676811f6d991d2857/esp/Light_Node/Light_Node.ino#L197

Will this help improve responsiveness? The tests I've done with the light node show about a second between motion and light turning on and a second between the controller's timer expiring and the light turning off. Is this because of the delay? My guess is yes, but needs testing.

It's important to call delay of some duration regularly so that the node can process network traffic, according to [this.](https://arduino-esp8266.readthedocs.io/en/latest/reference.html#timing-and-delays)

**Comment by dangyuluo** [comment]
This delay is to avoid reading the sensor too frequently. DHT11 needs some time to collect data before it can have meaningful output. 
I'll try to use another method to do this.

**Comment by khaledhassan** [comment]
Good catch, I didn't think of that. 

Maybe we can use the ```millis()``` function to re-read the sensor only after a certain amount of time but run ```loop()``` more quickly. 

In other words, sometimes an execution of ```loop()``` would read from the sensor and sometimes it wouldn't, but the sensor would still be read on a regular basis.

**Comment by dangyuluo** [comment]
That's what I'm gonna do.
