### ISSUE TITLE
ESP: Don't reuse a JsonBuffer for multiple tasks

### ISSUE THREAD

**Issue by khaledhassan** [khaledhassan/HAS#15]
https://github.com/khaledhassan/HAS/blob/509ca071d19776bacb1e5be676811f6d991d2857/esp/AC_Node/src/AC_Node.cpp#L18

According to [this page](https://arduinojson.org/doc/pitfalls/), you should not reuse the same JsonBuffer for multiple tasks. 

They recommend allocating it on the stack inside a function and letting it be deallocated at the end of that function as creating more JSON objects inside the same buffer will cause it to run out of room. 

I experienced a problem with this when testing the Light Node's motion sensor. After a while, all of the JSON messages sent were empty or didn't have all of the data they were supposed to. Using a local StaticJsonBuffer inside each function solved the problem.

The documentation also suggests reading [this page about the library's memory model](https://arduinojson.org/doc/memory/).

Lastly, the [ArduinoJson assistant](https://arduinojson.org/assistant/) looks pretty cool!

**Comment by dangyuluo** [comment]
Will change it.
