### ISSUE TITLE
AC_Node WiFi.begin() needs ssid and password?

### ISSUE THREAD

**Issue by khaledhassan** [khaledhassan/HAS#17]
https://github.com/khaledhassan/HAS/blob/509ca071d19776bacb1e5be676811f6d991d2857/esp/AC_Node/src/AC_Node.cpp#L43

See https://github.com/khaledhassan/HAS/blob/509ca071d19776bacb1e5be676811f6d991d2857/esp/Light_Node/Light_Node.ino#L31
 
for an example of this other syntax. I think this is why we had trouble connecting to Hao's router before we reset it, that day in the HSC library.

**Comment by dangyuluo** [comment]
Will set a password.
